version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.9
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo Build started on `date`
      - echo Installing dependencies...
      
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - echo Running tests...
      - # Add your test commands here
      - echo Tests completed successfully
      
  build:
    commands:
      - echo Build phase started on `date`
      - echo Building the application...
      - echo "Current directory contents:"
      - ls -la
      - echo "Infrastructure directory contents:"
      - ls -la infrastructure/
      - echo "Copying app-infrastructure.yaml to root for CloudFormation..."
      - cp infrastructure/app-infrastructure.yaml ./app-infrastructure.yaml
      - echo "Root directory contents after copy:"
      - ls -la
      - echo "Verifying app-infrastructure.yaml exists:"
      - cat app-infrastructure.yaml | head -5
      
  post_build:
    commands:
      - echo Post-build phase started on `date`
      - echo Build completed on `date`
      - echo Preparing artifacts...

artifacts:
  files:
    - '**/*'
  name: BuildArtifact

cache:
  paths:
    - '/root/.npm/**/*'
    - '/root/.cache/pip/**/*'