AWSTemplateFormatVersion: '2010-09-09'
Description: 'Application Infrastructure deployed by CI/CD Pipeline'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name'

Resources:
  # Lambda Function (example serverless component)
  HelloWorldFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'cicd-hello-world-${Environment}'
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps({
                      'message': 'Hello from CI/CD Pipeline!',
                      'environment': 'dev',
                      'timestamp': str(context.aws_request_id)
                  })
              }

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  LambdaFunctionName:
    Description: 'Lambda function name'
    Value: !Ref HelloWorldFunction
    
  LambdaFunctionArn:
    Description: 'Lambda function ARN'
    Value: !GetAtt HelloWorldFunction.Arn