AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodePipeline for CI/CD Pipeline'

Parameters:
  GitHubOwner:
    Type: String
    Description: 'GitHub repository owner'
    
  GitHubRepo:
    Type: String
    Description: 'GitHub repository name'
    
  GitHubBranch:
    Type: String
    Default: 'main'
    Description: 'GitHub branch to track'
    
  GitHubToken:
    Type: String
    NoEcho: true
    Description: 'GitHub personal access token'

Resources:

  # CodePipeline with multi-region support
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: 'cicd-pipeline'
      RoleArn: 
        Fn::ImportValue: 'cicd-iam-roles-CodePipelineServiceRoleArn'
      ArtifactStores:
        - Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: !Sub 'codepipeline-artifacts-${AWS::AccountId}-us-east-1'
        - Region: us-west-1
          ArtifactStore:
            Type: S3
            Location: !Sub 'codepipeline-artifacts-${AWS::AccountId}-us-west-1'
      Stages:
        # Source Stage
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceOutput
                
        # Build Stage
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: 
                  Fn::ImportValue: 'cicd-codebuild-CodeBuildProjectName'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
                
        # Deploy Dev Stage (us-east-1)
        - Name: DeployDev
          Actions:
            - Name: CreateChangeSetDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                StackName: 'cicd-app-stack-dev'
                ChangeSetName: 'cicd-app-changeset-dev'
                TemplatePath: 'BuildOutput::app-infrastructure.yaml'
                Capabilities: CAPABILITY_IAM
                RoleArn: 
                  Fn::ImportValue: 'cicd-iam-roles-CloudFormationServiceRoleArn'
                ParameterOverrides: |
                  {
                    "Environment": "dev"
                  }
              InputArtifacts:
                - Name: BuildOutput
              Region: us-east-1
              RunOrder: 1
              
            - Name: ExecuteChangeSetDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                StackName: 'cicd-app-stack-dev'
                ChangeSetName: 'cicd-app-changeset-dev'
              Region: us-east-1
              RunOrder: 2

        # Manual Approval Stage
        - Name: ManualApproval
          Actions:
            - Name: ApprovalForProduction
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: 'Please review the Dev deployment in us-east-1 and approve for Production deployment to us-west-1'
                ExternalEntityLink: !Sub 'https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/stackinfo?stackId=cicd-app-stack-dev'

        # Deploy Prod Stage (us-west-1)
        - Name: DeployProd
          Actions:
            - Name: CreateChangeSetProd
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                StackName: 'cicd-app-stack-prod'
                ChangeSetName: 'cicd-app-changeset-prod'
                TemplatePath: 'BuildOutput::app-infrastructure.yaml'
                Capabilities: CAPABILITY_IAM
                RoleArn: 
                  Fn::ImportValue: 'cicd-iam-roles-CloudFormationServiceRoleArn'
                ParameterOverrides: |
                  {
                    "Environment": "prod"
                  }
              InputArtifacts:
                - Name: BuildOutput
              Region: us-west-1
              RunOrder: 1
              
            - Name: ExecuteChangeSetProd
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                StackName: 'cicd-app-stack-prod'
                ChangeSetName: 'cicd-app-changeset-prod'
              Region: us-west-1
              RunOrder: 2

  # GitHub Webhook
  GitHubWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Name: 'cicd-github-webhook'
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubToken
      Filters:
        - JsonPath: '$.ref'
          MatchEquals: !Sub 'refs/heads/${GitHubBranch}'
      TargetPipeline: !Ref CodePipeline
      TargetAction: SourceAction
      TargetPipelineVersion: !GetAtt CodePipeline.Version
      RegisterWithThirdParty: true

Outputs:
  CodePipelineName:
    Description: 'Name of the CodePipeline'
    Value: !Ref CodePipeline
    Export:
      Name: !Sub '${AWS::StackName}-CodePipelineName'
      
  CodePipelineArtifactsBucketEast:
    Description: 'S3 bucket for CodePipeline artifacts in us-east-1'
    Value: !Sub 'codepipeline-artifacts-${AWS::AccountId}-us-east-1'
    Export:
      Name: !Sub '${AWS::StackName}-CodePipelineArtifactsBucketEast'

  CodePipelineArtifactsBucketWest:
    Description: 'S3 bucket for CodePipeline artifacts in us-west-1'
    Value: !Sub 'codepipeline-artifacts-${AWS::AccountId}-us-west-1'
    Export:
      Name: !Sub '${AWS::StackName}-CodePipelineArtifactsBucketWest'